### ISSUE TITLE
cassettes with multiple requests to URLs that only differ by query params don't seem to match on query params

### ISSUE THREAD

**Issue by jordan0day** [parroty/exvcr#11]
I have a cassette with two request-response pairs, and the two requests have similar URLs (the first request doesn't contain query params, the second does), however, exvcr seems to always match the first request.

So, something like this in my cassette's json:
````
{
  "request": {
    "url": "http://test"
  },
  "response": {
    "body": "no url params"
  }
},
{
  "request": {
    "url": "http://test?param=value
  },
  "response": {
    "body": "got url params"
  }
}
````
When running the test, the response body for two subsequent calls is
http://test -> no url params
http://test?param=value -> no url params

**Comment by parroty** [comment]
Please let me close with the above, at the moment. If you find any further issue/comment, please reopen or open another one, thanks.
