### ISSUE TITLE
Unable to use specific query parameters with custom cassettes

### ISSUE THREAD

**Issue by msawka** [parroty/exvcr#13]
There seems to be an issue with the Regex pattern matching in the [handler.ex's matching](https://github.com/parroty/exvcr/blob/master/lib/exvcr/handler.ex#L53) 
in which URLs that contain query paramters aren't able to be used (params after the ? will break the match).  Here's an example:

```elixir
test "handles failure" do
  use_cassette "failure", custom: true do
    case HTTPoison.post("https://myurl.com?auth_token=123abc", "", [], []) do
      {:ok, %HTTPoison.Response{status_code: 204}} ->
        Logger.debug("Success")
      {:error, %HTTPoison.Error{id: _, reason: reason}} ->
        Logger.error("Failure")
    end
  end    
end
```

failure.json:
```javascript
[
  {
    "request": {
      "body": "",
      "headers": {
        "Content-Type": "application/json"
      },
      "method": "post",
      "options": {
        "connect_timeout": 5000
      },
      "url": "https://myurl.com?auth_token=123abc"
    },
    "response": {
      "body": "",
      "headers": {
      },
      "status_code": 400,
      "type": "error"
    }
  }
]
```

A work-around is to use regex in the JSON to ignore the query params, or to simply leave the query params off:
failure.json:
```javascript
[
  {
    "request": {
      "body": "",
      "headers": {
        "Content-Type": "application/json"
      },
      "method": "post",
      "options": {
        "connect_timeout": 5000
      },
      "url": "https://myurl.com.+"
    },
    "response": {
      "body": "",
      "headers": {
      },
      "status_code": 400,
      "type": "error"
    }
  }
]
```

But, this can be problematic if you need to ensure the query params are set correctly.  Adding a Regex.escape (see below) seems to resolve the issue for this case, but looks like it breaks other pattern matching in URLs within the JSON:

```elixir
pattern = Regex.compile!("^#{Regex.escape(response[:request].url)}.*$")
```

**Comment by msawka** [comment]
Sorry for the delayed response, i think that makes a lot of sense

**Comment by parroty** [comment]
Thanks for the reply. I've pushed a related commit. I think this allows either String or Regexp, though the format is getting tricker..

**Comment by parroty** [comment]
I've pushed as v0.4.0, and I'm closing this item at the moment. If you get any further comment, please reopen or open another one.
