### ISSUE TITLE
How to use ExVCR with Finch?

### ISSUE THREAD

**Issue by danicuki** [parroty/exvcr#166]
My project uses [Finch](https://github.com/keathley/finch) to make parallel HTTP requests.

I tried to add VCR to my tests, but the HTTP requests are still happening.

Here is my test:
```elixir
defmodule MyClientTest do
  use ExUnit.Case, async: true
  use ExVCR.Mock #, adapter: ExVCR.Adapter.Httpc

  setup do
    ExVCR.Config.cassette_library_dir("fixture/vcr_cassettes")
    :ok
  end

  test "list_apps" do
    use_cassette "list_apps" do
      list_apps = MyClient.list_apps
      assert MyClient.list_apps == ["app1", "app2"]
    end
  end

end
```

I see a `list_apps.json` file in the `fixture/vcr_cassettes`, but its content is only `[]`

Here is my MyClient module:

```elixir
defmodule MyClient do
  alias Finch.Response

  def child_spec do
    {Finch,
     name: __MODULE__,
     pools: %{
       "https://myapp.com" => [size: 100]
     }}
  end

  def applications_response do
    :get
    |> Finch.build("https://myapp.com/v2/apps.json")
    |> Finch.request(__MODULE__)
  end

  def handle_applications_response({:ok, %Response{body: body}}) do
    body
    |> Jason.decode!()
    end
  end

  def list_apps do
    handle_applications_response(applications_response())
  end

end

```

How to apply VCR to this example?

**Comment by reisub** [comment]
I believe this issue can now be closed since Finch support is there and [documented in the README](https://github.com/parroty/exvcr#example-with-finch).

**Comment by Stratus3D** [comment]
I'm using this with Finch as documented and haven't had any issues. This can be closed.

**Comment by parroty** [comment]
Thanks for the follow-up 🙇
