### ISSUE TITLE
Return value from test in use_cassette macros

### ISSUE THREAD

**Issue by jhosteny** [parroty/exvcr#17]
Thanks for the great library!

It'd be really useful to be able to return the value from the body of the use_cassette macro, e.g.:

```elixir
defmacro use_cassette(:stub, options, test) do
  quote do
    stub_fixture = "stub_fixture_#{ExVCR.Util.uniq_id}"
    stub = prepare_stub_record(unquote(options), adapter_method)
    recorder = Recorder.start([fixture: stub_fixture, stub: stub, adapter: adapter_method])

    mock_methods(recorder, adapter_method)

    try do
      value = unquote(test)
      if options_method[:clear_mock] || unquote(options)[:clear_mock] do
        :meck.unload(adapter_method.module_name)
      end
      value
    after
      # do nothing
    end
  end
end
```

If this seems reasonable, I'll submit a patch.

**Comment by parroty** [comment]
Thanks for the comment, I think it's reasonable (I wasn't caring much about this part). I appreciate the patch!

**Comment by parroty** [comment]
Sorry taking time. After the commit above, the return value should be available like the following.

```elixir
test "return values from the block" do
  value = use_cassette "return_value_from_block" do
    1
  end
  assert value == 1
end
```

I'm closing at the moment, but if you find any remaining item, please reopen or open another one.
