### ISSUE TITLE
Add a delay to response?

### ISSUE THREAD

**Issue by jordan0day** [parroty/exvcr#23]
I'm wondering if there's any ability to add a delay before ExVCR sends its response to the HTTP Client? 

I'm trying to track down a bug where I'm expecting a timeout to happen, but the timeout is not occurring -- it would be helpful to replicate this situation using an ExVCR cassette where I could have ExVCR not respond for some configurable amount of time.

I glanced through the ExVCR code and didn't see anywhere obvious where this sort of functionality was already in place, so I'm wondering if adding it would be useful for other people? I also understand trying to trigger timeouts really isn't ExVCR's job, so I'm unsure if adding that feature would be a bad idea, but I thought I might take a crack at it and send a PR otherwise.

**Comment by parroty** [comment]
Thanks for the feedback. Adding a delay might be a little side direction from the mocking, but as long as it's optional, having the feature might be useful.

PR is great :-)

**Comment by jordan0day** [comment]
After looking through the ExVCR source I realized adding delays probably wouldn't be useful, since the underlying HTTP client library is being mocked out by ExVCR -- meaning whatever timeout functionality that client uses wouldn't end up being triggered anyway.

For anyone else trying to do this sort of thing (you want to trigger a timeout in your testing), it might be more useful to use a project like HTTParrot for that particular test.

**Comment by parroty** [comment]
OK, I was misunderstanding the point.
