### ISSUE TITLE
Erro with Meck

### ISSUE THREAD

**Issue by gullitmiranda** [parroty/exvcr#24]
I have tried to use but I have had this error. 

```
  1) test post events (Keenex.Events.Test)
     test/keenex/events_test.exs:12
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:ibrowse], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 392]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 347]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 202]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 239]}]}}
     stacktrace:
       src/meck_proc.erl:111: :meck_proc.set_expect/2
       src/meck.erl:227: :meck.expect/3
       (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:537: Enum.each/2
       test/keenex/events_test.exs:13
```

This project tests also gave the same problem.

**Comment by parroty** [comment]
Can I ask how the test is executed? (command and options). I'm not confident from the error message, but if it's compile-related, how about executing like the following?

    MIX_ENV=test mix do clean, compile, test

If possible, access to the code is great. I tried to execute `https://github.com/gullitmiranda/keenex`, but I couldn't see the same error.

**Comment by gullitmiranda** [comment]
I'm using the [azk](http://azk.io), so I have a totally isolated environment.
https://github.com/gullitmiranda/keenex#contributing

- Versions of elixir and dependencies:

```shell
$ azk shell

# env | grep MIX
MIX_ENV=test

# elixir --version
Elixir 1.0.5

# mix deps
* idna 1.0.2 (Hex package)
  locked at 1.0.2 (idna)
  ok
* exactor 2.1.2 (Hex package)
  locked at 2.1.2 (exactor)
  ok
* ssl_verify_hostname 1.0.5 (Hex package)
  locked at 1.0.5 (ssl_verify_hostname)
  ok
* meck 0.8.3 (Hex package)
  locked at 0.8.3 (meck)
  ok
* poison 1.3.1 (Hex package)
  locked at 1.3.1 (poison)
  ok
* jsx 2.4.0 (Hex package)
  locked at 2.4.0 (jsx)
  ok
* exjsx 3.1.0 (Hex package)
  locked at 3.1.0 (exjsx)
  ok
* hackney 1.2.0 (Hex package)
  locked at 1.2.0 (hackney)
  ok
* httpoison 0.7.0 (Hex package)
  locked at 0.7.0 (httpoison)
  ok
* httpotion 1.0.0 (Hex package)
  locked at 1.0.0 (httpotion)
  ok
* ibrowse 4.1.1 (git://github.com/cmullaparthi/ibrowse.git)
  locked at 5ee4a80
  ok
* exvcr 0.4.1 (git://github.com/parroty/exvcr.git)
  locked at e4d90c0
  ok
```
- Clean, compile and test:

```shell
# mix do clean, compile, test
Compiled lib/keenex/event_collections.ex
Compiled lib/keenex/events.ex
Compiled lib/keenex/base.ex
Compiled lib/keenex.ex
Compiled lib/keenex/http.ex
Generated keenex app
test/keenex/event_collections_test.exs:12: warning: variable context is unused
test/keenex/events_test.exs:12: warning: variable context is unused
test/keenex/event_collections_test.exs:14: warning: variable response is unused
test/keenex/events_test.exs:14: warning: variable response is unused


  1) test post to event collection (Keenex.EventCollections.Test)
     test/keenex/event_collections_test.exs:12
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:ibrowse], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 392]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 347]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 202]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 239]}]}}
     stacktrace:
       src/meck_proc.erl:111: :meck_proc.set_expect/2
       src/meck.erl:227: :meck.expect/3
       (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:537: Enum.each/2
       test/keenex/event_collections_test.exs:13



  2) test post events (Keenex.Events.Test)
     test/keenex/events_test.exs:12
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:ibrowse], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 392]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 347]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 202]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 239]}]}}
     stacktrace:
       src/meck_proc.erl:111: :meck_proc.set_expect/2
       src/meck.erl:227: :meck.expect/3
       (elixir) lib/enum.ex:537: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:537: Enum.each/2
       test/keenex/events_test.exs:13



Finished in 0.5 seconds (0.2s on load, 0.3s on tests)
2 tests, 2 failures

Randomized with seed 277862
```

**Comment by parroty** [comment]
Thanks for the detailed information. I could reproduce the error through the `azk` image you have shown.
But I cannot simulate the error in my local environment yet.

One difference I noticed is the erlang version. The `azk` image seems using erlang v18 - `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 7.0.1` and my local one is erlang v17 - `Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 6.3.1`. One quick solution might be using older version. 

I haven't been able to isolate the issue, but the `.travis.yml` of `https://github.com/eproxus/meck` seems to use erlang v17, and might be good to check from `meck` side too.

**Comment by gullitmiranda** [comment]
I will create an image with erlang v17 and see if the problem persists.

If that is the problem, I believe it is interesting open an issue in Meck to report the problem with erlang v18. What do you think?

**Comment by parroty** [comment]
That helps. If the error reason can be isolated, reporting to meck may be an option.

**Comment by gullitmiranda** [comment]
Unfortunately the problem persists even using Erlang v17 and Elixir 1.0.4. :cry:

```shell
$ iex --version
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.0.4
```

**Comment by parroty** [comment]
Hmm, I'm retrying, but haven't been able to find out a difference between my local OSX environment (working) and the azk image (not working).

Can you possibly reproduce the same issue outside of azk? I'm not so familiar with azk/docker operations, and having difficulty to isolate the issue.

By the way, some of the interactive operation fails on azk commands. Is there any notes or clue from the environment side?
```
% azk shell -- erl
Eshell V6.4  (abort with ^G)
1> *** Terminating erlang (nonode@nohost)
```

**Comment by gullitmiranda** [comment]
As soon as possible I will raise a machine with Ubuntu in Digital Ocean to run the tests.

Regarding the AZK, how you're going through a command to the shell, if this command is interactive you must use the flag `-t`.

Two ways to do what you need:

```shell
$ azk shell -t -- erl
# or
$ azk shell
$ erl
```

-
I opened an [issue](https://github.com/eproxus/meck/issues/148#issuecomment-123226402) in meck to try to remedy this problem.
Obitive the following response:

> It looks like you don't have cover on your path. The cover module is part of the tools application, which I just noticed that Meck is not depending on. Did you run this inside a release you created?

This `cover` would be any dependence on `exvcr` or some other package?

**Comment by parroty** [comment]
The `cover` module is a built-in coverage analysis tool which `excoveralls` are depending on.  It might be being pulled through dependency chain of `exvcr`. 

http://www.erlang.org/doc/man/cover.html

**Comment by gullitmiranda** [comment]
It seems to me I do not have the cover on my system. It should be installed with Erlang or is some separated package?

If separate how can I install?

```elixir
iex(1)> :cover.start
** (UndefinedFunctionError) undefined function: :cover.start/0 (module :cover is not available)
    :cover.start()
```

**Comment by parroty** [comment]
I think it's installed along with Erlang. 

```
Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :cover.start
{:ok, #PID<0.60.0>}
iex(2)>
```

**Comment by parroty** [comment]
http://www.erlang.org/faq/tools.html

----
7.4  What code testing tools and suites exist for and in Erlang/OTP?

A test suite is especially useful for making sure that "improvements" to the system haven't broken     something. The test system for Erlang. The test server can be used for testing your project and it includes test suites for the Erlang emulator and erlang stdlib.

The standard Erlang/OTP installation includes cover, a test coverage tool.

----

ExVCR does not directly dependent cover and I'm not sure enough why it's causing the issue, though.

**Comment by gullitmiranda** [comment]
I believe the cover only affects EzVCR tests, since it uses the `excoveralls`.

I will find out because the `cover` is not installed.

**Comment by gullitmiranda** [comment]
Missed the erlang-tools package. 

I will add it to elixir image and run the tests again as soon as possible.
http://pkgs.alpinelinux.org/package/testing/x86_64/erlang-tools

**Comment by gullitmiranda** [comment]
After installing the erlang-tools package testing returned to work. So closing this issue.
For instructions that are using docker, the image I created is [gullitmiranda/elixir](https://registry.hub.docker.com/u/gullitmiranda/elixir/).

Note: It's working including Elixir v1.0.5 and Erlang / OTP 18.

**Comment by parroty** [comment]
Thanks for the update.
