### ISSUE TITLE
Error String.Chars not implemented for :multipart in :hackney

### ISSUE THREAD

**Issue by waynehoover** [parroty/exvcr#34]
I have a somewhat complicated HTTPoision i.e :hackney POST i'm doing:

`HTTPoison.post!("/photos", {:multipart, [{:file, "path/to/file", { ["form-data"], [name: "\"photo\"", filename: "\"path/to/file\""]},[]}]}, [], [recv_timeout: 30000])`

and this works when I run the test without VCR, but when I run through VCR I get this error:

```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:multipart, [{:file, "/path/to/file", {["form-data"], [name: "\"photo\"", filename: "\"/path/to/file\""]}, []}]}
     stacktrace:
       (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
       (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
       lib/exvcr/adapter/hackney/converter.ex:6: ExVCR.Adapter.Hackney.Converter."parse_request_body (overridable 1)"/1
       lib/exvcr/adapter/hackney.ex:40: ExVCR.Adapter.Hackney.generate_keys_for_request/1
       lib/exvcr/handler.ex:22: ExVCR.Handler.get_response_from_cache/2
       lib/exvcr/handler.ex:13: ExVCR.Handler.get_response/2
       (hackney) :hackney.request(:post, ...}, [recv_timeout: 30000])
       (httpoison) lib/httpoison/base.ex:394: HTTPoison.Base.request/9
       ...
```

Without knowing much of the code, maybe instead of `to_string` we use `IO.inspect` here https://github.com/parroty/exvcr/blob/master/lib/exvcr/adapter/hackney/converter.ex#L61

**Comment by parroty** [comment]
Thanks for the report. As you indicated, `to_string` seems failing. I tried to put a fallback clause with `inspect` and pushed to master. Is it possible for you to try with the change?

**Comment by waynehoover** [comment]
Thank you that fixed it.

**Comment by parroty** [comment]
Thanks!
