### ISSUE TITLE
Provide ability to set vcr and custom folders via `config.exs`

### ISSUE THREAD

**Issue by pvdvreede** [parroty/exvcr#37]
I want to set a custom folder for the cassettes and can do this in the `setup_all` macro in my tests which is fine, but if I want to run the mix tasks I need to supply my custom dirs every time I run it - even though it is something that never changes.

Is it possible to set the directories in my `config.exs` file? That way I can create a `test.exs` that gets included from `config.exs` when in the test env and it is available for both the mix tasks and the test runner.

Thanks.

**Comment by parroty** [comment]
Thanks for the feedback, it makes sense. I'll try to check, but please allow some time.

**Comment by parroty** [comment]
I am making trial to add `config.exs` setting as in the following.
  https://github.com/parroty/exvcr#default-configs
Is it possible for you to try? It's pushed into `master` though it's not published to `hex` yet.

**Comment by parroty** [comment]
I've pushed as `v0.7.1`. I'm closing at the moment, but if there's remaining issues, please reopen or open another one.
