### ISSUE TITLE
Running `mix vcr` without custom cassette folder gives annoying message

### ISSUE THREAD

**Issue by douglascamata** [parroty/exvcr#49]
If you do not create the `custom_cassette` folder in the same level as your cassete folder, running `mix vcr` will print an annoying message like this in the end: 

```
** (ExVCR.PathNotFoundError) Specified path 'fixture/custom_cassettes' for reading cassettes was not found.
    lib/exvcr/task/runner.ex:34: ExVCR.Task.Runner.find_json_files/1
    lib/exvcr/task/runner.ex:23: ExVCR.Task.Runner.read_cassettes/1
    lib/exvcr/task/runner.ex:17: anonymous fn/1 in ExVCR.Task.Runner.show_vcr_cassettes/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

My only configuration for `exvcr` is `ExVCR.Config.cassette_library_dir("fixture/vcr_cassettes")`.

IMHO, if the custom cassette folder is not found it should just be ignored.

**Comment by parroty** [comment]
Thanks for the report. I'll be pushing the fix to ignore the path.

**Comment by douglascamata** [comment]
Thanks!
