### ISSUE TITLE
mix tasks doesn't take into account "cassette_library_dir" config

### ISSUE THREAD

**Issue by StanBright** [parroty/exvcr#82]
Hi,

If I set the **cassette_library_dir** directly into a module or inside a ```Mix.Config```, the new directory is used when running the tests; however, it seems it is disregarded by the "mix" tasks. 

I have set "preferred_cli_env:". Do you think I'm missing something or it is a general issue?

Everything seems fine by using the default dir - "fixture/vcr_cassettes". I'm trying to set it globally to "test/fixtures/vcr_cassettes".

**Comment by alakra** [comment]
Bump.

**Comment by parroty** [comment]
I'm assuming this item is covered by #88 and closing at the moment.
If you find remaining issue, please reopen or open another one.
