### ISSUE TITLE
Stubbing POST?

### ISSUE THREAD

**Issue by drapergeek** [parroty/exvcr#89]
I've been using the `use_cassette :stub, [status_code: 500]` option for a while and it works great for `GET` requests. When I moved to using a `POST` however, the `stub` doesn't seem to be catching anything.

Things I've tried:
* Specifying the URL
* Specifying the `post` method as `"POST"` or `"post"`
* Upgrading to the newest version of VCR.

I'm using the Hackney adapter and the request is going through HTTPoison. Any ideas would be really helpful. Thanks!

**Comment by drapergeek** [comment]
Looks like this is directly related to #61

**Comment by parroty** [comment]
Thanks for the comment. This item was being sunk for a while, and will try to revisit.

**Comment by parroty** [comment]
The above is a trial to ignore request_body when it's not used. 
Does the test condition matches your expectation?

**Comment by drapergeek** [comment]
That's exactly what I need! Thanks!

**Comment by parroty** [comment]
Thanks for the reply. I've pushed to the hex.
